### ISSUE TITLE
Something is going on with the Detection ratio for Australia

### ISSUE THREAD

**Issue by CatdBD** [benflips/nCovForecast#128]
A picture says a thousand words... 

<img width="803" alt="Screen Shot 2020-06-05 at 2 38 00 pm" src="https://user-images.githubusercontent.com/11154277/83837673-58eb9f80-a73a-11ea-924e-61034de4bec2.png">

All I did was go to the page, select Australia from the drop-down, twiddle the log/linear radio buttons them scroll down. I don't think reproduceability will be an issue on this one.

**Comment by CatdBD** [comment]
Oh! It's because we had -1 deaths one day isn't it?

**Comment by benflips** [comment]
Crikey.  Yes, didn't take into account the possibility of negative deaths :-/  I'll make a quick fix to that now..

**Comment by benflips** [comment]
Fixed.  Thanks for the quick eyes, @CatdBD.
