### ISSUE TITLE
New URL?

### ISSUE THREAD

**Issue by AntoineSoetewey** [benflips/nCovForecast#172]
Dear @benflips,

It seems that the url http://covid19forecast.science.unimelb.edu.au/ is broken. Do you have a new one to replace it?

Thanks in advance!

**Comment by benflips** [comment]
Hi @AntoineSoetewey. 

Not sure what happened, but is seems to be working now.  Thanks for the heads up.

**Comment by AntoineSoetewey** [comment]
Thanks !
