### ISSUE TITLE
Label of active cases 

### ISSUE THREAD

**Issue by mjcampy** [benflips/nCovForecast#23]
The label of active cases does not change with the new slider. Low priority.

**Comment by mjcampy** [comment]
"Now | In 10 days (min-max)"

**Comment by benflips** [comment]
It shouldn't change, because the projections still go out to ten days.  The adjustment is in the other direction -- the number of days back in time used to fit the model.  Might be we need a clearer way of communicating this?

**Comment by mjcampy** [comment]
I didn't grasp at first. Possible to have a small vertical bar for where fit starts on the plot? or different color data points that are used in the fit? I now can see the where the min-max dotted lines start when I move the slider.

**Comment by benflips** [comment]
Soon to be deployed plots employ different colours as suggested

**Comment by mjcampy** [comment]
thank you for the response/attention, but thanks more for the great app.
