### ISSUE TITLE
Number of predicted cases can exceed total population 

### ISSUE THREAD

**Issue by mtomasini** [benflips/nCovForecast#3]
Since the evolution of the number of cases is a simple exponential, in small countries (e.g. Switzerland) this simple model predicts that most (and often all) of the population will get infected. Now, this seems to me quite improbable. 

I will read some literature today and see if I can find something about that, so that the total number of predicted cases would not exceed the maximal expected number of cases (i.e. expected by theoretical models) - nor the total population.

**Comment by benflips** [comment]
We would need population sizes and an SIR model backend to do this well.  For the meantime, most of the really silly numbers will come from poor detection estimates.  These will get better as the epidemic grows, but we could pool countries (e.g., Europe) as an interim measure to improve detection estimate.  We'd be pooling across very different State responses, but probably better than estimating from tiny sample sizes at this stage.  I'll work on a way to implement this feature in a way that we can easily drop it in a few weeks when numbers are up.

**Comment by danbolnick** [comment]
Getting population sizes; will also look for age-structure data to project mortality risk more accurately perhaps?

**Comment by benflips** [comment]
Legend.  Thanks.

**Comment by benflips** [comment]
Have taken the simple expedient of not projecting detection-corrected estimates, because we clearly breach densities that matter to SIR dynamics.
