### ISSUE TITLE
Fix active cases to account for recovered reporting 

### ISSUE THREAD

**Issue by henryhcraig** [benflips/nCovForecast#36]
Now that case recoveries have started to be reported (eg https://www.health.gov.au/sites/default/files/documents/2020/04/coronavirus-covid-19-at-a-glance-coronavirus-covid-19-at-a-glance-infographic_1.pdf) the active case numbers don't need to rely on the "22 day" rule.

Could this be fixed? It will have a significant effect on active case numbers!

**Comment by benflips** [comment]
We are working to build country-specific versions of the site now.  So in principle, yes, this might be something we can do.  Good idea.

**Comment by benflips** [comment]
Done.  (For all countries except US and Canada, whose reporting seems to be different from others.)

**Comment by henryhcraig** [comment]
Well done!
