### ISSUE TITLE
Aspect ratio of the plots is sometimes wrong

### ISSUE THREAD

**Issue by CatdBD** [benflips/nCovForecast#44]
Seems to happen after switching from Global to State-based and back.

**Comment by CatdBD** [comment]
Some examples:

![image](https://user-images.githubusercontent.com/11154277/78957154-d96d9580-7b27-11ea-8940-834126b96c37.png)

![image](https://user-images.githubusercontent.com/11154277/78957146-d70b3b80-7b27-11ea-8bd8-07a118a19435.png)

**Comment by benflips** [comment]
I can't reproduce this.  Can you give me some local details: browser, OS?

**Comment by benflips** [comment]
OK, I can reproduce it... sometimes.  Reload resolves it.  That's going to be tricky to find...

**Comment by CatdBD** [comment]
Yeah... It's a tricky one. Sorry for pointing out a doozy haha

**Comment by CatdBD** [comment]
Let me know if you still want browser and OS info :)

**Comment by melissamakin123** [comment]
Fixed by #72

**Comment by melissamakin123** [comment]
Reverting with https://github.com/benflips/nCovForecast/pull/73 as this made things worse (plot much wider than screen width) on mobile all the time, not just for this weird edge case.

**Comment by melissamakin123** [comment]
Fixed by #105 - no longer have tabs.  Thanks @CatdBD for reporting this.
