### ISSUE TITLE
Running data locally

### ISSUE THREAD

**Issue by pssguy** [benflips/nCovForecast#47]
Hi, i would like to build a project based on your scripts. Love what you have done on the shiny app

I have a project created in RStudio cloned from this github but am not sure how to progress from there. I would like to run in RStudio if possible
There is no getDatNew.R script which you refer to. i have tried running getData.R - which has necessitated creating a dat/Global folder - but hit errors when I reach this code

```
> system("Rscript detection/estGlobalV2.R 'Global'", wait = TRUE)
Warning message:
package 'addreg' was built under R version 3.6.3 
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
Calls: load -> readChar
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'dat/'Global'/cacheData.RData', probable reason 'No such file or directory'
Execution halted
[1] 1
> load("dat/Global/estDeconv.RData")
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'dat/Global/estDeconv.RData', probable reason 'No such file or directory'
> 
```

Any help much appreciated

**Comment by benflips** [comment]
Hi Andrew.

We just merged some big changes yesterday  in a hurry and we haven’t updated Readme. You need to run getData.R before anything else (takes about ten minutes). But it needs a directory structure in the dat/ folder. A dat/Global and dat/[country] for each of available_countries.

B


Excuse the brevity: sent from my phone.

On 11 Apr 2020, at 02:53, Andrew Clark <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, i would like to build a project based on your scripts. Love what you have done on the shiny app

I have a project created in RStudio cloned from this github but am not sure how to progress from there. I would like to run in RStudio if possible
There is no getDatNew.R script which you refer to. i have tried running getData.R - which has necessitated creating a dat/Global folder - but hit errors when I reach this code

> system("Rscript detection/estGlobalV2.R 'Global'", wait = TRUE)
Warning message:
package 'addreg' was built under R version 3.6.3
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
Calls: load -> readChar
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'dat/'Global'/cacheData.RData', probable reason 'No such file or directory'
Execution halted
[1] 1
> load("dat/Global/estDeconv.RData")
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'dat/Global/estDeconv.RData', probable reason 'No such file or directory'
>


Any help much appreciated

**Comment by benflips** [comment]
I have updated the readme.  This should get you through until we address #42

**Comment by pssguy** [comment]
Thanks Ben. Yes that is what I hacked to obtain current info.

Do I understand from the code that individual US states could be made available, as per Australia? I know that does not tie into your country projection but I would like to have the data available to work on if it is not too much of a problem

**Comment by benflips** [comment]
The app does state-level for all available_countries, including US.

Excuse the brevity: sent from my phone.

On 12 Apr 2020, at 04:53, Andrew Clark <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks Ben. Yes that is what I hacked to obtain current info.

Do I understand from the code that individual US states could be made available, as per Australia? I know that does not tie into your country projection but I would like to have the data available to work on if it is not too much of a problem
