### ISSUE TITLE
No estDeconv.RData in dat/Global folder?

### ISSUE THREAD

**Issue by meoksuz** [benflips/nCovForecast#49]
Finally working side me. But have some errors for missing estDeconv.RData in dat/Global folder? and Possible number of cases now given imperfect detection table return zero argument

**Comment by meoksuz** [comment]
I have tried otherwise way generate cached data but have similar error:


Warning: Ignoring 10 observations
Warning: Ignoring 10 observations
Warning: Error in if: sıfır uzunluğunda argüman
  96: renderTable [H:\nCovForecast/app.R#255]
  95: func
  82: origRenderFunc
  81: output$tablePredTrue
   1: runApp
Warning: Error in :: 0 uzunluğunda argüman
  99: renderPlotly [H:\nCovForecast/app.R#276]
  98: func
  95: func
  82: origRenderFunc
  81: output$cfi
   1: runApp
Warning: Error in data.frame: arguments imply differing number of rows: 80, 0
  101: stop
  100: data.frame
   99: renderPlotly [H:\nCovForecast/app.R#308]
   98: func
   95: func
   82: origRenderFunc
   81: output$growthRate
    1: runApp
Warning: Error in if: sıfır uzunluğunda argüman
  96: renderTable [H:\nCovForecast/app.R#255]
  95: func
  82: origRenderFunc
  81: output$tablePredTrue
   1: runApp
Warning: Ignoring 10 observations
Warning: Ignoring 10 observations
Warning in log(active) : NaNs üretimi
Warning in log(active) : NaNs üretimi

**Comment by benflips** [comment]
If you checkout make_directories, delete your /dat and run getData.R it should make all directories and files you need.  Takes a while to run though.

**Comment by benflips** [comment]
This should all be much simpler now with #50 merged.
