### ISSUE TITLE
Forecast not refreshing when selecting a Country the second time on global_or_country

### ISSUE THREAD

**Issue by svalqui** [benflips/nCovForecast#53]
Forecast not refreshing when selecting a Country the second time on "Select global or country:"
The selection defaults to global, that is fine;
then if you select for example Australia, that works as well;
then if you select US (or any other of the countries), the page doesn't refresh.
Tested on Firefox v75.0; Chrome Version 81.0.4044.92

**Comment by benflips** [comment]
Thanks for pointing this out, Sergio.  My bug.  We've fixed it.
