### ISSUE TITLE
Add vertical line to indicate peak of infections as determined by time varying growth model

### ISSUE THREAD

**Issue by melissamakin123** [benflips/nCovForecast#78]
![image](https://user-images.githubusercontent.com/28580044/80446429-2cce4900-895a-11ea-9e90-0d1fc7a558e2.png)

**Comment by melissamakin123** [comment]
if ln A(t) = b t^2/2 + rt + lnA0, then peak should occur at t = -r/b.

**Comment by benflips** [comment]
closed with #92
